implemented validation and globalExceptionHandler
TarasYashchuk/BookStore pull request #5
Opened 2024-06-20 08:57 UTC by TarasYashchuk

2024-06-20 09:10 UTC, TarasYashchuk commented
Is it possible to add custom messages in my annotations and in global exception handler return default message ?

For example:
@NotNull(message = "Description is mandatory")
@Size(min = 1, message = "Description length must be greater than {min} characters")
@Constraint(validatedBy = {})
@Target({ ElementType.METHOD, ElementType.FIELD, ElementType.ANNOTATION_TYPE, ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)
public @interface Description {
    String message() default "Invalid Description";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}

In globalExceptionHandler:
private String getErrorMessage(ObjectError e) {
        return e.getDefaultMessage();
    }
   
Because in some cases messages in looks like this
![image](https://github.com/TarasYashchuk/BookStore/assets/122051047/f35d9051-c3fe-4fc2-abd5-9169f1115366)

2024-06-20 10:22 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @Title
You can use instead of creating your own validation annotation
```suggestion
    @NotBlank(message = "Title must not be null or empty")
```

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @Isbn
It's good to have Isbn validator and URL validator, bu for other fields you can use `@NotBlank(message...) ` for String type and for BigDecimal price:
```
@NotNull(message = "Price must not be null")
@Positive(message = "Price must not be negative")
```

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/UpdateBookRequestDto.java
> +    @Title
same here
You can even use for example
`@Size(min = 10, max = 13, message = "Required length 10-13 digits")`

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    public BookDto save(@RequestBody @Valid CreateBookRequestDto requestDto) {
What about validation update dto? 
Also, you can add `@Positive Long id` where is needed and add `@Validated` under the controller

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/BookDto.java
>  public class BookDto {
Is it response DTO? If so, don't need to validate fields

2024-06-20 10:22 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
spring-boot-starter-validation provides this dependency, so if yout have one, don't need to add it

2024-06-20 10:22 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>validation-api</artifactId>
the same

To check if some dependency already provides other, you can call in console `mvn dependency:tree` and check if dependency already exists

2024-06-20 10:22 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>javax.el</artifactId>
Why do you need this dependency?

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/validator/CoverImageUrlValidator.java
> +    public void initialize(CoverImage constraintAnnotation) {
remove

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/validator/CoverImageUrlValidator.java
> +        if (coverImage == null || coverImage.trim().isEmpty()) {
```suggestion
        return coverImage != null && IMAGE_URL_PATTERN
                .matcher(coverImage)
                .matches();
```

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/validator/Isbnalidator.java
> +    public void initialize(Isbn constraintAnnotation) {
remove

2024-06-20 10:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/validator/Isbnalidator.java
> +
```suggestion
```

2024-06-21 07:54 UTC, Elena-Bruyako requested changes
Good job! Let's improve it a little

2024-06-21 07:54 UTC, Elena-Bruyako commented on pom.xml
> +            <version>${spring-boot-starter-validation.version}</version>
```suggestion
```

2024-06-21 07:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    private static final int TITLE_MAX_LENGTH = 20;
Don't need to create all these constants, just use values in annotation Size

2024-06-21 07:54 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/UpdateBookRequestDto.java
> +    private static final int TITLE_MAX_LENGTH = 20;
Don't need to create all these constants, just use values in annotation Size

2024-06-21 12:59 UTC, okuzan requested changes

2024-06-21 12:59 UTC, okuzan commented on src/main/java/mate/academy/dto/UpdateBookRequestDto.java
> +    @NotNull(message = "Description is mandatory")
not null doesn't make sense - if it's optional, let it be nullable, if it's required - it should be notBlank

2024-06-21 13:17 UTC, okuzan approved these changes

2024-06-21 13:17 UTC, okuzan commented on src/main/java/mate/academy/dto/UpdateBookRequestDto.java
> +    @NotBlank(message = "Description is mandatory")
IIRC description is optional - so better remove it

2024-06-21 13:23 UTC, merged